version: '3.8'

services:
  app:
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    #     target: app
    image: ghcr.io/alex2304/planning-poker:latest
    ports:
      - "${HOST_PORT:-8000}:8000"
    environment:
      GUNICORN_BIND: "${GUNICORN_BIND:-0.0.0.0:8000}"
      GUNICORN_WORKERS: "${GUNICORN_WORKERS:-3}"
      GUNICORN_TIMEOUT: "${GUNICORN_TIMEOUT:-120}"
